// interface

interface fifo_if #(
	parameter int NUM_FOLDS  = 7,
	parameter int FOLD_WIDTH = 23
  ) (
	input logic clk
  );
  
	// Reset and DUT inputs
	logic rst_n;
	logic en_i;
	logic wr_en_i;
	logic [FOLD_WIDTH-1:0] folded_history_i [0:NUM_FOLDS-1];
	logic rd_en_i;
	logic misprediction_i;
  
	// DUT outputs
	logic fifo_full_o;
	logic fifo_empty_o;
	logic recovery_valid_o;
	logic [FOLD_WIDTH-1:0] recovery_folded_history_o [0:NUM_FOLDS-1];
  
	clocking drv_cb @(negedge clk);
	  output en_i;
	  output wr_en_i;
	  output folded_history_i;
	  output rd_en_i;
	  output misprediction_i;
	endclocking
  
	clocking mon_cb @(posedge clk);
	  default input #0;
  
	  input rst_n;
	  input en_i;
	  input wr_en_i;
	  input folded_history_i;
	  input rd_en_i;
	  input misprediction_i;
  
	  input fifo_full_o;
	  input fifo_empty_o;
	  input recovery_valid_o;
	  input recovery_folded_history_o;
	endclocking
  
	modport DRIVER (
	  clocking drv_cb,
	  input rst_n
	);
  
	modport MONITOR (
	  clocking mon_cb
	);
  
	modport DUT (
	  input  clk,
	  input  rst_n,
	  input  en_i,
	  input  wr_en_i,
	  input  folded_history_i,
	  input  rd_en_i,
	  input  misprediction_i,
	  output fifo_full_o,
	  output fifo_empty_o,
	  output recovery_valid_o,
	  output recovery_folded_history_o
	);
  
endinterface

// sequence item
class fifo_item extends uvm_sequence_item;

	// Generated by sequences and driven into the DUT
	rand bit en;
	rand bit wr_en;
	rand bit rd_en;
	rand bit misprediction;
	rand bit [FOLD_WIDTH-1:0] data [0:NUM_FOLDS-1];

	// Captured by the monitor
	bit rst_n;
	bit full;
	bit empty;
	bit recovery_valid;
	bit [FOLD_WIDTH-1:0] recovery_data [0:NUM_FOLDS-1];

	// Mostly active traffic, with occasional global-enable stalls.
	constraint useful_c {
		en dist {
			1 := 9,
			0 := 1
		};
	}

	`uvm_object_utils_begin(fifo_item)
		`uvm_field_int(en,            UVM_DEFAULT)
		`uvm_field_int(wr_en,         UVM_DEFAULT)
		`uvm_field_int(rd_en,         UVM_DEFAULT)
		`uvm_field_int(misprediction, UVM_DEFAULT)
		`uvm_field_sarray_int(data,   UVM_DEFAULT)

		`uvm_field_int(rst_n,          UVM_DEFAULT | UVM_NOCOMPARE)
		`uvm_field_int(full,           UVM_DEFAULT | UVM_NOCOMPARE)
		`uvm_field_int(empty,          UVM_DEFAULT | UVM_NOCOMPARE)
		`uvm_field_int(recovery_valid, UVM_DEFAULT | UVM_NOCOMPARE)
		`uvm_field_sarray_int(
			recovery_data,
			UVM_DEFAULT | UVM_NOCOMPARE
		)
	`uvm_object_utils_end

	function new(string name = "fifo_item");
		super.new(name);
	endfunction

endclass

class fifo_sequencer extends uvm_sequencer #(fifo_item);

	`uvm_component_utils(fifo_sequencer)

	function new(string name = "fifo_sequencer",uvm_component parent = null);
		super.new(name, parent);
	endfunction

endclass


class fifo_driver extends uvm_driver #(fifo_item);

	`uvm_component_utils(fifo_driver)

	virtual fifo_if #(NUM_FOLDS, FOLD_WIDTH) vif;

	function new(string name = "fifo_driver",uvm_component parent = null);
		super.new(name, parent);
	endfunction

	function void build_phase(uvm_phase phase);
		super.build_phase(phase);

		if (!uvm_config_db#(virtual fifo_if #(NUM_FOLDS, FOLD_WIDTH))::get(this, "", "vif", vif)) begin
			`uvm_fatal("FIFO/DRV/NOVIF","fifo_if was not configured")
		end
	endfunction

	task drive_idle();
		vif.drv_cb.en_i            <= 1'b0;
		vif.drv_cb.wr_en_i         <= 1'b0;
		vif.drv_cb.rd_en_i         <= 1'b0;
		vif.drv_cb.misprediction_i <= 1'b0;

		for (int i = 0; i < NUM_FOLDS; i++) begin
				vif.drv_cb.folded_history_i[i] <= '0;
			end
	endtask

	task drive_item(fifo_item item);
		vif.drv_cb.en_i            <= item.en;
		vif.drv_cb.wr_en_i         <= item.wr_en;
		vif.drv_cb.rd_en_i         <= item.rd_en;
		vif.drv_cb.misprediction_i <= item.misprediction;

		for (int i = 0; i < NUM_FOLDS; i++) begin
			vif.drv_cb.folded_history_i[i] <= item.data[i];
		end
	endtask

	task run_phase(uvm_phase phase);
		drive_idle();

		// Do not begin sequence traffic during reset.
		wait (vif.rst_n === 1'b1);

		forever begin
			seq_item_port.get_next_item(req);

			// drv_cb is triggered on the falling edge.
			@(vif.drv_cb);
			drive_item(req);

			seq_item_port.item_done();
		end
	endtask

endclass


class fifo_monitor extends uvm_component;

	`uvm_component_utils(fifo_monitor)
	virtual fifo_if #(NUM_FOLDS, FOLD_WIDTH) vif;
	uvm_analysis_port #(fifo_item) ap;

	function new(string name = "fifo_monitor",uvm_component parent = null);
		super.new(name, parent);
		ap = new("ap", this);
	endfunction

	function void build_phase(uvm_phase phase);
		super.build_phase(phase);

		if (!uvm_config_db#(virtual fifo_if #(NUM_FOLDS, FOLD_WIDTH))::get(this, "", "vif", vif)) begin
		`uvm_fatal(
			"FIFO/MON/NOVIF",
			"fifo_if was not configured"
		)
		end
	endfunction

	task run_phase(uvm_phase phase);
		fifo_item t;

		forever begin
			@(vif.mon_cb);

			t = fifo_item::type_id::create("observed");

			// Capture DUT inputs for this cycle.
			t.rst_n         = vif.mon_cb.rst_n;
			t.en            = vif.mon_cb.en_i;
			t.wr_en         = vif.mon_cb.wr_en_i;
			t.rd_en         = vif.mon_cb.rd_en_i;
			t.misprediction = vif.mon_cb.misprediction_i;

			// Capture DUT outputs after the rising-edge update.
			t.full           = vif.mon_cb.fifo_full_o;
			t.empty          = vif.mon_cb.fifo_empty_o;
			t.recovery_valid = vif.mon_cb.recovery_valid_o;

			for (int i = 0; i < NUM_FOLDS; i++) begin
				t.data[i] = vif.mon_cb.folded_history_i[i];
				t.recovery_data[i] = vif.mon_cb.recovery_folded_history_o[i];
			end

			ap.write(t);
		end
	endtask

endclass

// scoreboard
class fifo_scoreboard extends uvm_component;

	`uvm_component_utils(fifo_scoreboard)

	uvm_analysis_imp #(fifo_item, fifo_scoreboard) imp;

	typedef bit [FOLD_WIDTH-1:0] fold_entry_t [NUM_FOLDS];
	fold_entry_t model_q[$];

	int unsigned checked_cycles;

	function new(string name = "fifo_scoreboard",uvm_component parent = null);
		super.new(name, parent);
		imp = new("imp", this);
	endfunction

	function void write(fifo_item t);
		bit read_accept;
		bit write_accept;

		fold_entry_t popped;
		int old_size;

		// Reset the reference model and check reset outputs.
		if (t.rst_n !== 1'b1) begin
		model_q.delete();

		if (t.full !== 1'b0)
			`uvm_error("FIFO/SB/RESET","fifo_full_o is not 0 during reset"
			)

		if (t.empty !== 1'b1)
			`uvm_error("FIFO/SB/RESET","fifo_empty_o is not 1 during reset"
			)

		if (t.recovery_valid !== 1'b0)
			`uvm_error("FIFO/SB/RESET","recovery_valid_o is not 0 during reset"
			)

		for (int i = 0; i < NUM_FOLDS; i++) begin
			if (t.recovery_data[i] !== '0)
			`uvm_error("FIFO/SB/RESET_DATA",$sformatf("recovery fold[%0d] is not 0 during reset",i))
		end

		return;
		end

		old_size = model_q.size();

		read_accept = t.en && t.rd_en && (old_size != 0);

		write_accept = t.en && t.wr_en && ((old_size != DEPTH) || read_accept);

		// A simultaneous full read/write first removes the oldest
		// entry and then installs the replacement entry.
		if (read_accept)
		popped = model_q.pop_front();

		if (write_accept)
		model_q.push_back(t.data);

		if (t.empty !== (model_q.size() == 0))
		`uvm_error("FIFO/SB/EMPTY",$sformatf("empty=%0b expected=%0b model_size=%0d",t.empty,(model_q.size() == 0),model_q.size()))

		if (t.full !== (model_q.size() == DEPTH))
		`uvm_error("FIFO/SB/FULL",$sformatf("full=%0b expected=%0b model_size=%0d",t.full,(model_q.size() == DEPTH),model_q.size()))

		if (t.recovery_valid !== (read_accept && t.misprediction))
		`uvm_error("FIFO/SB/VALID",$sformatf("recovery_valid=%0b expected=%0b",t.recovery_valid,(read_accept && t.misprediction)))

		foreach (t.recovery_data[i]) begin
		if (read_accept && t.misprediction) begin
			if (t.recovery_data[i] !== popped[i])
			`uvm_error("FIFO/SB/DATA",$sformatf("fold[%0d]=%h expected=%h",i,t.recovery_data[i],popped[i]))
		end
		else if (t.recovery_data[i] !== '0) begin
			`uvm_error("FIFO/SB/ZERO",$sformatf("fold[%0d]=%h while recovery is invalid",i,t.recovery_data[i]))
		end
		end

		checked_cycles++;
	endfunction

	function void report_phase(uvm_phase phase);
		super.report_phase(phase);

		`uvm_info("FIFO/SB/SUMMARY",$sformatf("Checked %0d active FIFO cycles",checked_cycles),UVM_LOW)
	endfunction

endclass

// agent

class fifo_agent extends uvm_agent;

	`uvm_component_utils(fifo_agent)

	fifo_sequencer seqr;
	fifo_driver    drv;
	fifo_monitor   mon;

	function new(string name = "fifo_agent",uvm_component parent = null);
		super.new(name, parent);
	endfunction

	function void build_phase(uvm_phase phase);
		super.build_phase(phase);

		// Monitoring is needed for both active and passive agents.
		mon = fifo_monitor::type_id::create("mon",this);

		if (get_is_active() == UVM_ACTIVE) begin
			seqr = fifo_sequencer::type_id::create("seqr",this);
			drv = fifo_driver::type_id::create("drv",this);
		end
	endfunction

	function void connect_phase(uvm_phase phase);
		super.connect_phase(phase);

		if (get_is_active() == UVM_ACTIVE) begin
			drv.seq_item_port.connect(seqr.seq_item_export);
		end
	endfunction

endclass

// environment
class fifo_env extends uvm_env;

	`uvm_component_utils(fifo_env)

	fifo_agent      agent;
	fifo_scoreboard sb;

	function new(string name = "fifo_env",uvm_component parent = null);
		super.new(name, parent);
	endfunction

	function void build_phase(uvm_phase phase);
		super.build_phase(phase);
		agent = fifo_agent::type_id::create("agent",this);
		sb = fifo_scoreboard::type_id::create("sb",this);
	endfunction

	function void connect_phase(uvm_phase phase);
		super.connect_phase(phase);
		agent.mon.ap.connect(sb.imp);
	endfunction

endclass

// test
class fifo_test extends uvm_test;

	`uvm_component_utils(fifo_test)

	fifo_env env;

	function new(string name = "fifo_test",uvm_component parent = null);
		super.new(name, parent);
	endfunction

	function void build_phase(uvm_phase phase);
		super.build_phase(phase);
		uvm_config_db#(uvm_active_passive_enum)::set(this,"env.agent","is_active",UVM_ACTIVE);
		env = fifo_env::type_id::create("env",this);
	endfunction

	task run_phase(uvm_phase phase);
		fifo_corner_seq corner;
		fifo_random_seq random_seq;

		phase.raise_objection(this);

			// corner = fifo_corner_seq::type_id::create("corner");
			// corner.start(env.agent.seqr);
			random_seq = fifo_random_seq::type_id::create("random_seq");
			random_seq.start(env.agent.seqr);

			// Allow the final driven item to be sampled and checked.
			repeat (2) @(posedge env.agent.drv.vif.clk);

		phase.drop_objection(this);
	endtask

endclass

// tb top

module tb_top;

	import uvm_pkg::*;
	import fifo_uvm_pkg::*;

	logic clk = 1'b0;

	always #5ns clk = ~clk;

	fifo_if #(
		.NUM_FOLDS  (NUM_FOLDS),
		.FOLD_WIDTH (FOLD_WIDTH)
	) vif (
		.clk (clk)
	);

	checkpoint_fifo_buffer #(
		.DEPTH      (DEPTH),
		.NUM_FOLDS  (NUM_FOLDS),
		.FOLD_WIDTH (FOLD_WIDTH)
	) dut (
		.clk                       (vif.clk),
		.rst_n                     (vif.rst_n),
		.en_i                      (vif.en_i),
		.wr_en_i                   (vif.wr_en_i),
		.folded_history_i          (vif.folded_history_i),
		.rd_en_i                   (vif.rd_en_i),
		.misprediction_i           (vif.misprediction_i),
		.fifo_full_o               (vif.fifo_full_o),
		.fifo_empty_o              (vif.fifo_empty_o),
		.recovery_valid_o          (vif.recovery_valid_o),
		.recovery_folded_history_o (vif.recovery_folded_history_o)
	);

	initial begin
		vif.rst_n = 1'b0;
		repeat (3) @(negedge clk);
		vif.rst_n = 1'b1;
	end

	initial begin
		uvm_config_db#(virtual fifo_if #(NUM_FOLDS, FOLD_WIDTH))::set(null,"uvm_test_top.env.agent.*","vif",vif);
		run_test("fifo_test");
	end

endmodule